import ReduxProvider from "@/redux/provider/ReduxProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { InterTight } from "@/fonts/Fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Guicopay - Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${InterTight.variable} antialiased`}
      >
        <ReduxProvider>
          {children}
          <Toaster richColors position="top-center" /> {/* 👈 add this */}
        </ReduxProvider>
      </body>
    </html>
  );
}
